### ISSUE TITLE
Parse Error, when using CostRequest

### ISSUE THREAD

**Issue by faruqy87** [zuhriyansauqi/raja-ongkir-sdk#2]
I'm using CostRequest with single courier,
            
            request = new CostRequest("501", PlaceTypes.CITY, "574", PlaceTypes.SUBDISTRICT, 1700,
                    new ArrayList<>(Arrays.asList(Couriers.JALUR_NUGRAHA_EKAKURIR)),
                    null, null, null, null);
            task = new GetCostTask(rajaOngkir, request, this);
            task.execute();

But I can't get on didExecuted, always reach onError with PARSE_ERROR

**Comment by zuhriyansauqi** [comment]
Fixed. Thanks.
